// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_package.proto

#include "control_package.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ControlPackage::ControlPackage(
    ::_pbi::ConstantInitialized) {}
struct ControlPackageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ControlPackageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ControlPackageDefaultTypeInternal() {}
  union {
    ControlPackage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ControlPackageDefaultTypeInternal _ControlPackage_default_instance_;
static ::_pb::Metadata file_level_metadata_control_5fpackage_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_control_5fpackage_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_5fpackage_2eproto = nullptr;

const uint32_t TableStruct_control_5fpackage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ControlPackage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ControlPackage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ControlPackage_default_instance_._instance,
};

const char descriptor_table_protodef_control_5fpackage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025control_package.proto\032\023rendering_job.p"
  "roto\"\020\n\016ControlPackage*4\n\023RenderMessageD"
  "etail\022\013\n\007RMD_TRY\020\000\022\020\n\014RMD_FEEDBACK\020\001P\000b\006"
  "proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_control_5fpackage_2eproto_deps[1] = {
  &::descriptor_table_rendering_5fjob_2eproto,
};
static ::_pbi::once_flag descriptor_table_control_5fpackage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_5fpackage_2eproto = {
    false, false, 126, descriptor_table_protodef_control_5fpackage_2eproto,
    "control_package.proto",
    &descriptor_table_control_5fpackage_2eproto_once, descriptor_table_control_5fpackage_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_control_5fpackage_2eproto::offsets,
    file_level_metadata_control_5fpackage_2eproto, file_level_enum_descriptors_control_5fpackage_2eproto,
    file_level_service_descriptors_control_5fpackage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_5fpackage_2eproto_getter() {
  return &descriptor_table_control_5fpackage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_5fpackage_2eproto(&descriptor_table_control_5fpackage_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RenderMessageDetail_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_control_5fpackage_2eproto);
  return file_level_enum_descriptors_control_5fpackage_2eproto[0];
}
bool RenderMessageDetail_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ControlPackage::_Internal {
 public:
};

ControlPackage::ControlPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ControlPackage)
}
ControlPackage::ControlPackage(const ControlPackage& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ControlPackage* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ControlPackage)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ControlPackage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ControlPackage::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ControlPackage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fpackage_2eproto_getter, &descriptor_table_control_5fpackage_2eproto_once,
      file_level_metadata_control_5fpackage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ControlPackage*
Arena::CreateMaybeMessage< ::ControlPackage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ControlPackage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
